on:
  release:
    types: [published]

name: Upload an Asset to Release

jobs:
  run:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare release artifact
        run: .github/workflows/scripts/prepare-release-asset.sh

      - name:  Upload asset
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} AdyenPaymentShopware6.zip --clobber
          # ref_name takes the reference of the entity that triggered this workflow, for eg. a branch (branch name), a release (tag name), workflow etc. 
